Add skip logic to all STIGbyID states
plus3it/ash-linux-formula pull request #309
Opened 2021-03-12 20:14 UTC by ferricoxide

Closes #301 

Facilitates use of the full suite of STIG handlers by allowing disablement of problematic, individual STIG-handlers

2021-04-30 20:55 UTC, eemperor requested changes

2021-04-30 20:55 UTC, eemperor commented on ash-linux/el7/STIGbyID/cat2/RHEL-07-040410.sls
> +{%- set skipIt = salt.pillar.get('ash-linux:lookup:skip-stigs', []) %}
Duplicate line.

2021-04-30 20:55 UTC, eemperor commented on ash-linux/el7/STIGbyID/cat2/RHEL-07-040730.sls
> +{%- set skipIt = salt.pillar.get('ash-linux:lookup:skip-stigs', []) %}
Duplicate line.

2021-04-30 21:24 UTC, eemperor requested changes

2021-04-30 21:24 UTC, eemperor commented on ash-linux/el7/STIGbyID/cat2/RHEL-07-040160.sls
> +  {%- for cfgExtra in salt.file.find('/etc/profile.d', maxdepth='0', type='f') %}
Salt 3003 needs the `maxdepth` value to be an integer and minimum depth of `1`.

```suggestion
  {%- for cfgExtra in salt.file.find('/etc/profile.d', maxdepth=1, type='f') %}
```

2021-04-30 21:26 UTC, eemperor commented on ash-linux/el7/STIGbyID/cat2/RHEL-07-040160.sls
> +  {%- for cfgExtra in salt.file.find('/etc/profile.d', maxdepth='0', type='f') %}
You probably need to rebase your branch since this was fixed recently.

2021-05-03 13:25 UTC, ferricoxide commented on ash-linux/el7/STIGbyID/cat2/RHEL-07-021050.sls
> +{%- set globWrDirs = salt['cmd.shell']('find / -path /proc -prune -o -perm /002 -type d -print').split('\n') %}
I probably _can_, but, `salt.file.find` doesn't have a 100% overlap between what it's able to do and what the OS-specific `find`-command is able to do. Overall, the focus of this PR was simply to add execution-exceptions rather than alter existing functionality.

2021-05-03 13:34 UTC, ferricoxide commented on ash-linux/el7/STIGbyID/cat2/RHEL-07-040070.sls
> +{%- set skipIt = salt.pillar.get('ash-linux:lookup:skip-stigs', []) %}
Goddammit. Looks like when I was trying to merge back from upstream, it nuked out the if-else from several files.

2021-05-03 15:39 UTC, ferricoxide commented on ash-linux/el7/STIGbyID/cat2/RHEL-07-040160.sls
> +  {%- for cfgExtra in salt.file.find('/etc/profile.d', maxdepth='0', type='f') %}
Change made, locally, will push, shortly

2021-05-03 15:41 UTC, ferricoxide commented on ash-linux/el7/STIGbyID/cat2/RHEL-07-040730.sls
> +{%- set skipIt = salt.pillar.get('ash-linux:lookup:skip-stigs', []) %}
Change made, locally, will push, shortly

2021-05-03 15:41 UTC, ferricoxide commented on ash-linux/el7/STIGbyID/cat2/RHEL-07-040410.sls
> +{%- set skipIt = salt.pillar.get('ash-linux:lookup:skip-stigs', []) %}
Change made, locally, will push, shortly

2021-05-03 15:51 UTC, eemperor commented on ash-linux/el7/STIGbyID/cat2/RHEL-07-021050.sls
> +{%- set globWrDirs = salt['cmd.shell']('find / -path /proc -prune -o -perm /002 -type d -print').split('\n') %}
Okay.

2021-05-03 16:43 UTC, eemperor approved these changes
🚀 Let's give it a go!

2021-05-03 17:17 UTC, merged